defmodule AshDesk.Repo.Migrations.AddCustomerIdAndSubjectToConversations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :subject, :text

      add :customer_id,
          references(:users,
            column: :id,
            name: "conversations_customer_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:conversations, "conversations_customer_id_fkey")

    alter table(:conversations) do
      remove :customer_id
      remove :subject
    end
  end
end
