defmodule AshDesk.Repo.Migrations.AddSupportDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:conversations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "open"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "conversations_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :assigned_agent_id,
          references(:users,
            column: :id,
            name: "conversations_assigned_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:conversations, "conversations_organization_id_fkey")

    drop constraint(:conversations, "conversations_assigned_agent_id_fkey")

    drop table(:conversations)
  end
end
